name: Build Release

on:
  workflow_dispatch:
    inputs:
      versionName:
        required: true
        description: This releases version name
        default: "ALPHA - 1.20"
      versionCode:
        required: true
        description: This releases version code
        default: "1320"
      preRelease:
        description: 'Mark as pre-release'
        required: true
        type: boolean
      description:
        required: false
        description: Description of this release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set Version
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{github.event.inputs.versionCode}}
          versionName: ${{github.event.inputs.versionName}}

      - name: Build Signed APK
        run: |
          echo "${{ secrets.keystore }}" | base64 -d > $GITHUB_WORKSPACE/signing-key.jks
          chmod +x ./gradlew
          ./gradlew assembleRelease -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/signing-key.jks -Pandroid.injected.signing.store.password=${{ secrets.keystore_password }} -Pandroid.injected.signing.key.alias=${{ secrets.key_alias }} -Pandroid.injected.signing.key.password=${{ secrets.key_password }}

      - name: Release
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          tag="${{ github.event.inputs.versionCode }}"
          git tag "$tag"
          git push origin "$tag"
          gh release create "$tag" \
            --title "${{ github.event.inputs.versionName }}" \
            --notes "${{ github.event.inputs.description }}" \
            app/build/outputs/apk/release/app-release.apk
          if ["${{github.event.inputs.preRelease}}" == "true"]; then gh release edit "$tag" -p; fi
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'