name: Build Debug

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Get short SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Set Version
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: app/build.gradle.kts
          versionName: "DEBUG - ${{ steps.short-sha.outputs.sha }}"

      - name: Build Debug APK
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk